[package]
name = "mmd_physics_solver"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
mmd-anim-physics-bullet = { path = "vendor/mmd-anim-physics-bullet", default-features = false, features = ["native"] }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
